/**
 * Site content — copy from assets/new_stuff.md, releases from src/data/discography.json
 * (generated by scripts/fetch-discography.py from assets/spotify_&_apple_music_links.md + iTunes).
 */
import discography from "../data/discography.json";

export const MEDIA = `${import.meta.env.BASE_URL}media`;
const media = (p) => (p ? `${MEDIA}/${p}` : null);
const mediaSm = (p) => (p ? `${MEDIA}/${p.replace("covers/", "covers/sm/")}` : null);

const SPOTIFY_ARTIST = discography.artist.spotify;
const APPLE_ARTIST = discography.artist.apple;
const YOUTUBE = "https://www.youtube.com/@Krayaura";
const BEHANCE = "https://www.behance.net/koketsoramogale1";

export const site = {
  name: "Krayaura",
  tagline: "Nostalgia, fun, and confidence — sound and visuals from Pretoria.",
  roles: ["Rapper", "Singer", "Producer", "Creative Director", "Graphic Designer"],
  location: "Pretoria, South Africa",
  handle: "@krayaura",
  // A 4:5 crop of him from the CRASH shoot (scripts/copy-media.py)
  portrait: `${MEDIA}/brand/portrait.jpg`,
  portraitSm: `${MEDIA}/brand/portrait-sm.jpg`,
  booking: {
    label: "Book / collab",
    // Opens the DM thread straight away (the app on phones)
    href: "https://ig.me/m/krayaura",
    note: "DM me on Instagram for bookings, features & collabs",
  },
  bio: [
    "I'm Koketso Ramogale — Krayaura — from Pretoria. I've been making beats since high school and produced for other artists before I believed in my own voice. I taught myself to mix, master, rap and sing.",
    "Inspired by the vibrant cartoons of the 2000s and my passion for the South African music industry, my creations radiate joy, nostalgia, and imagination.",
    "I employ bold and warm colours, especially shades of orange, coupled with expressive strokes and captivating sans-serif fonts.",
  ],
  // His own words from the bio, pulled out as the About headline quote
  quote: "My ultimate ambition is to leave a lasting mark on the South African music industry through my unique creative vision.",
  platforms: {
    spotify: SPOTIFY_ARTIST,
    apple: APPLE_ARTIST,
    youtube: YOUTUBE,
    behance: BEHANCE,
  },
};

/** YouTube video per release, where one exists */
const VIDEO_FOR = {
  crash: "aDGTLwUDDTE",
  "south-side-baby": "Zal8Xlb_RGs",
  "bad-for-me": "cQA7FduD2yQ",
  "wrote-me-a-letter": "qQ0VqT5W934",
  "no-calls": "DeWlKhHrqQc",
  "ice-it": "i7QpbU9jTQI",
  "lets-get-smoothies": "FKbOK6ZVb9w",
};

const TONES = ["red", "gold", "blue"];

/**
 * Everything the audio engine needs to play one preview.
 * @typedef {{ key: string, title: string, subtitle: string, cover: string, coverSm: string,
 *             preview: string, apple: string, spotify: string|null, releaseId: string }} Playable
 */
function toPlayable(release, track) {
  return {
    key: `${release.id}:${track.n ?? 1}`,
    title: track.title,
    subtitle: release.type === "album" ? `${release.title} · Track ${track.n}` : `${release.year} · Single`,
    features: track.features,
    cover: media(release.cover),
    coverSm: mediaSm(release.cover),
    preview: track.preview,
    apple: track.apple || release.apple,
    spotify: release.spotify,
    releaseId: release.id,
    release: release.title,
  };
}

export const releases = discography.releases.map((r, i) => {
  const lead = r.tracks.find((t) => t.popular) || r.tracks[0];
  return {
    ...r,
    cover: media(r.cover),
    coverSm: mediaSm(r.cover),
    tone: TONES[i % TONES.length],
    meta: r.type === "album" ? `Album · ${r.trackCount} tracks` : "Single",
    popular: r.popular || r.tracks.some((t) => t.popular),
    youtube: VIDEO_FOR[r.id] ? `https://www.youtube.com/watch?v=${VIDEO_FOR[r.id]}` : null,
    lead: lead ? toPlayable(r, lead) : null,
    playables: r.tracks.filter((t) => t.preview).map((t) => toPlayable(r, t)),
  };
});

export const releaseById = Object.fromEntries(releases.map((r) => [r.id, r]));

/** Spotify "Popular" (from the links file) */
export const popular = discography.popular;

export const crashAlbum = releaseById.crash;

export const crashStory = {
  title: "CRASH",
  kicker: "The album · 14 tracks · Nov 2025",
  cover: crashAlbum?.cover,
  spotify: crashAlbum?.spotify,
  apple: crashAlbum?.apple,
  href: crashAlbum?.spotify || SPOTIFY_ARTIST,
  story: [
    "I'll be honest this one took years. From making beats since high school to producing for other artists and helping them shine before I even believed in my own voice.",
    "From being obsessed with music, studying it, exploring every genre I could find, to learning everything I could. From teaching myself how to mix, master, rap, sing, and build a unique sound.",
    "From going to school to become a visual communicator, creating concepts, scripts, designs, and ideas that shaped how I express myself today.",
  ],
  punchlines: ["I'm not just a producer.", "I'm not just a rapper.", "I'm not just a singer."],
  finaleLead: "I'm a",
  finale: "Full creator",
  finaleTail: "and every version of me had to grow for this moment to exist.",
  credit: "Posted by Krayaura",
};

/** YouTube carousel — titles from YouTube oEmbed */
export const videos = [
  { id: "aDGTLwUDDTE", title: "Crash", kind: "Official Trailer" },
  { id: "9jAdO-_HJEo", title: "Day Dreaming", kind: "Short Film" },
  { id: "Zal8Xlb_RGs", title: "SouthSide Baby", kind: "Official Music Video" },
  { id: "cQA7FduD2yQ", title: "Bad For Me", kind: "Official Visualizer" },
  { id: "qQ0VqT5W934", title: "Wrote Me A Letter", kind: "Official Music Video" },
  { id: "DeWlKhHrqQc", title: "No Calls ft. Dioscuri & iloh vas", kind: "Official Visualizer" },
  { id: "i7QpbU9jTQI", title: "Ice It", kind: "Official Music Video" },
  { id: "FKbOK6ZVb9w", title: "Let's Get Smoothies", kind: "Official Music Video" },
  { id: "6jHgxM4CMew", title: "You Amazing", kind: "Reaction Vlog" },
].map((v, i) => ({
  ...v,
  index: String(i + 1).padStart(2, "0"),
  watchUrl: `https://www.youtube.com/watch?v=${v.id}`,
  embedUrl: `https://www.youtube.com/embed/${v.id}?rel=0&modestbranding=1&playsinline=1&vq=hd1080`,
  // 1280×720, no letterbox; yt-carousel falls back to sddefault/hqdefault if missing
  thumb: `https://i.ytimg.com/vi/${v.id}/maxresdefault.jpg`,
  // 320×180 webp (~5–11KB) for the side slides; the active one swaps up to maxres once it has loaded
  thumbLite: `https://i.ytimg.com/vi_webp/${v.id}/mqdefault.webp`,
  thumbLiteFallback: `https://i.ytimg.com/vi/${v.id}/mqdefault.jpg`,
  thumbFallbacks: [
    `https://i.ytimg.com/vi/${v.id}/sddefault.jpg`,
    `https://i.ytimg.com/vi/${v.id}/hqdefault.jpg`,
  ],
}));

/**
 * Design rows. Each shows its image in-flow at every size (width/height keep the aspect ratio, no CLS).
 * `releases` makes a row a fan of sleeves that opens the lightbox as a playable gallery.
 * Descriptions are facts only; an empty one renders no line.
 */
export const projects = [
  {
    id: "behance-portfolio",
    title: "Portfolio",
    tag: "Behance",
    description: "Selected graphic design, photography and videography — the full portfolio on Behance.",
    href: "https://www.behance.net/gallery/181718011/Koketso-Ramogale-Portfolio",
    cover: `${MEDIA}/behance/koketso-ramogale-portfolio/cover.jpg`,
    width: 808,
    height: 632,
    gallery: "koketso-ramogale-portfolio",
  },
  {
    id: "behance-connected",
    title: "Connected to the Future",
    tag: "Behance",
    description: null,
    href: "https://www.behance.net/gallery/176724099/Connected-to-the-future",
    cover: `${MEDIA}/behance/connected-to-the-future/cover.jpg`,
    width: 808,
    height: 632,
    gallery: "connected-to-the-future",
  },
  {
    id: "cover-art",
    title: "Cover art",
    tag: "5 releases",
    description:
      "Sleeves for CRASH (Nov 2025), Signal (May 2026), Wrote Me A Letter (Dec 2024), B.O.M.B (Dec 2023) and Let's Get Smoothies (Aug 2022).",
    href: BEHANCE,
    releases: ["crash", "signal", "wrote-me-a-letter", "bomb", "lets-get-smoothies"],
  },
  {
    id: "channel-world",
    title: "Channel World",
    tag: "Brand / YouTube",
    description: "Profile picture and banner for my YouTube channel.",
    href: YOUTUBE,
    // Full 2560×1440 channel art (resized), shown whole so the design reads
    cover: `${MEDIA}/brand/channel-banner-1600.jpg`,
    srcset: `${MEDIA}/brand/channel-banner-800.jpg 800w, ${MEDIA}/brand/channel-banner-1600.jpg 1600w`,
    width: 1600,
    height: 900,
  },
];

/**
 * Connect: `primary` ones are the two wide streaming cards (with their `cta`), the rest are stickers.
 * The mobile menu (nav.js) picks its icons from this list too, so keep the order.
 */
export const socials = [
  { label: "Instagram", icon: "instagram", href: "https://www.instagram.com/krayaura/" },
  { label: "TikTok", icon: "tiktok", href: "https://www.tiktok.com/@krayaura" },
  { label: "YouTube", icon: "youtube", href: YOUTUBE },
  { label: "Spotify", cta: "Follow on Spotify", icon: "spotify", href: SPOTIFY_ARTIST, primary: true },
  { label: "Apple Music", cta: "Add on Apple Music", icon: "apple", href: APPLE_ARTIST, primary: true },
  { label: "Behance", icon: "behance", href: BEHANCE },
];
